name: Set up environment
description: sets up the environment for a deploy

inputs:
  oidc-role:
    required: true
    description: the OIDC role to use
  aws-region:
    required: true
    description: the AWS region to use
  branch-specific-oidc-role:
    required: true
    description: the branch-specific OIDC role to use
  branch-specific-aws-region:
    required: true
    description: the branch-specific AWS region to use

runs:
  using: composite
  steps:
    - name: check out repository
      uses: actions/checkout@v3

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.branch-specific-oidc-role || inputs.oidc-role }}
        aws-region: ${{ inputs.branch-specific-aws-region || inputs.aws-region }}

    - name: read .nvmrc
      id: node_version
      shell: bash
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          **/node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}-3

    - name: install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile

    - name: set path
      shell: bash
      run: |
        echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
