name: Deploy to env

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    env:
      SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: upcase env name
        id: string-case
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ inputs.env }}

      - name: set up environment
        uses: ./.github/actions/set-up-env
        with:
          oidc-role: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          branch-specific-oidc-role: ${{ secrets[format('{0}_{1}', steps.string-case.outputs.uppercase, 'AWS_OIDC_ROLE_TO_ASSUME')] }}
          branch-specific-aws-region: ${{ secrets[format('{0}_{1}', steps.string-case.outputs.uppercase, 'AWS_DEFAULT_REGION')] }}

      - name: deploy
        run: |
          # When deploying multiple copies of this quickstart to the same AWS Account (not ideal), a prefix helps prevent stepping on each other.
          # This can optionally be set as an GitHub Actions Secret
          ./scripts/deploy.sh ${{ format('{0}{1}', secrets.STAGE_PREFIX, inputs.env) }}
