name: Destroy

on: delete

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  set-branch-name:
    name: set branch name
    uses: ./.github/workflows/set-and-validate-branch-name.yml
    with:
      run-validation: false
    secrets:
      STAGE_PREFIX: ${{ secrets.STAGE_PREFIX }}

  destroy:
    needs: set-branch-name
    # Protected branches should be designated as such in the GitHub UI.
    # So, a protected branch should never have this workflow run, since the branch should never be deleted.
    # This conditional is a backup mechanism to help prevent mistakes from becoming disasters.
    # This is a list of branch names that are commonly used for protected branches/environments.
    # Add/remove names from this list as appropriate.
    if: github.event.ref_type == 'branch' && !contains(fromJson('["master", "val", "production"]'), github.event.ref)
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: set up environment
        uses: ./.github/actions/set-up-env
        with:
          oidc-role: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          branch-specific-oidc-role: ${{ secrets[format('{0}_{1}', needs.set-branch-name.outputs.upcased-branch-name, 'AWS_OIDC_ROLE_TO_ASSUME')] }}
          branch-specific-aws-region: ${{ secrets[format('{0}_{1}', needs.set-branch-name.outputs.upcased-branch-name, 'AWS_DEFAULT_REGION')] }}

      - name: lock this branch to prevent concurrent builds
        run: ./.github/scripts/github_lock.sh ${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: destroy resources
        run: ./scripts/destroy.sh ${{ format('{0}{1}', secrets.STAGE_PREFIX, needs.set-branch-name.outputs.branch-name) }}
