name: Promote

on:
  push:
    branches:
      # - "bharvey-promote" TODO remove
      - "master"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  unit-tests:
    name: run unit tests
    uses: ./.github/workflows/unit-test.yml
    secrets:
      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID}}

  promote-dev:
    needs: [unit-tests]
    name: promote to dev
    uses: ./.github/workflows/deploy-to-env.yml
    with:
      env: dev
    secrets: inherit

  # cypress-dev:
  #   needs: [promote-dev, unit-tests]
  #   name: cypress tests for dev
  #   uses: ./.github/workflows/cypress-for-env.yml
  #   with:
  #     env: dev
  #   secrets: inherit

  # promote-val:
  #   needs: [cypress-dev, unit-tests]
  #   name: promote to val
  #   uses: ./.github/workflows/deploy-to-env.yml
  #   with:
  #     env: val
  #   secrets: inherit

  # cypress-val:
  #   needs: [promote-val, unit-tests]
  #   name: cypress tests for val
  #   uses: ./.github/workflows/cypress-for-env.yml
  #   with:
  #     env: val
  #   secrets: inherit

  # promote-production:
  #   needs: [cypress-val, unit-tests]
  #   name: promote to production
  #   uses: ./.github/workflows/deploy-to-env.yml
  #   with:
  #     env: production
  #   secrets: inherit

  # cypress-production:
  #   needs: [promote-production, unit-tests]
  #   name: cypress tests for production
  #   uses: ./.github/workflows/cypress-for-env.yml
  #   with:
  #     env: production
  #   secrets: inherit

  # notify-slack:
  #   needs: [promote-production, cypress-production]
  #   if: always()
  #   name: notify slack on failure
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: slack notification
  #       uses: rtCamp/action-slack-notify@v2
  #       if: env.SLACK_WEBHOOK_URL != '' && failure()
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_USERNAME: Deploy Alerts
  #         SLACK_ICON_EMOJI: ":bell:"
  #         SLACK_COLOR: ${{job.status}}
  #         SLACK_FOOTER: ""
  #         MSG_MINIMAL: actions url,commit,ref
