name: "Snyk Test"

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

permissions:
  security-events: write

jobs:
  snyk:
    name: Snyk Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run 'snyk test'
        uses: snyk/actions@0.3.0
        continue-on-error: true # To make sure that sarif upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --all-projects

      - name: Upload Snyk results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
